### ISSUE TITLE
.NET Core support TODO's

### ISSUE THREAD

**Issue by leppie** [IronScheme/IronScheme#53]
- [x] Tests (this runs, just need to add to CI)
- [x] Docs for running on .NET Core
- [x] ~~Compiled library loading support (this goes wrong somewhere...)~~

**Comment by leppie** [comment]
Linux instructions
```
wget https://dot.net/v1/dotnet-install.sh
chmod +x dotnet-install.sh
dotnet-install.sh --channel Current --runtime dotnet
export -p PATH="$HOME/.dotnet:$PATH"

cd <ironscheme dir>
dotnet IronScheme.ConsoleCore.dll
```

**Comment by leppie** [comment]
@weinholt Mind taking this for a spin? It is likely to be much better than Mono  ;p

**Comment by weinholt** [comment]
@leppie Pushed it to Docker hub as `weinholt/ironscheme:dotnet`. Used their official 3.0 runtime image. It starts, will try to see how much better it spins tomorrow.

**Comment by weinholt** [comment]
Industria's tests went from 2m 49s to 2m 0s. It also seems less crashy with .NET Core. So far so good.

**Comment by leppie** [comment]
> Industria's tests went from 2m 49s to 2m 0s. It also seems less crashy with .NET Core. So far so good.

Cool, I expected as much :D

**Comment by clorton** [comment]
This is exciting. Any change of getting the embedding samples working on .NET Core?

**Comment by leppie** [comment]
> This is exciting. Any change of getting the embedding samples working on .NET Core? (I am looking to move some code using IronScheme over to Linux.)

Just get the nuget package, and call `"your scheme".Eval()` basically. I removed the remoting stuff as that was never used and it not supported on .NET Core.

**Comment by clorton** [comment]
Hmm, build worked with a couple of warnings:

> /cms/framework/compartments/core-compartments.csproj : warning NU1701: Package 'IronScheme 0.9.115672' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

and execution bailed with the following:

> Caught exception during execution: The type initializer for 'IronScheme.RuntimeExtensions' threw an exception.

Looks like I may need the newer version you referenced above (1.0.212) maybe.

**Comment by leppie** [comment]
> Looks like I may need the newer version you referenced above (1.0.212).

Yes. 

You can either just get the `IronScheme,.Core` nuget (which is just the dll) or the zip with all the libs too.

You can safely ignore that compat warning. I have no idea if it can ever be removed :D
